export const STATIC_PRESENTATION_THEMES = [
    {
        id: "untitled-presentation-1",
        name: "Untitled Presentation",
        description: "Photo header with clean centered title.",
        previewImage: "https://cdn.pixabay.com/photo/2026/05/14/03/06/03-06-32-708_1280.jpg",
        presentation: {
            title: "Untitled Presentation",
            slides: [
                {
                    id: "slide-untitled-1",
                    background: "#ffffff",
                    backgroundImage: "https://cdn.pixabay.com/photo/2026/05/14/03/06/03-06-32-708_1280.jpg",
                    backgroundType: "image",
                    layers: [
                        {
                            id: "theme-1-overlay",
                            type: "shape",
                            shapeType: "rect",
                            x: 40,
                            y: 40,
                            width: 880,
                            height: 220,
                            fillColor: "rgba(255,255,255,0.88)",
                            strokeColor: "transparent",
                            strokeWidth: 0,
                            rotation: 0,
                            opacity: 0.88,
                            locked: false,
                        },
                        {
                            id: "theme-1-title",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "Untitled Presentation",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add title",
                            hasBeenEdited: true,
                            x: 70,
                            y: 70,
                            width: 820,
                            height: 110,
                            fontSize: 54,
                            fontFamily: "Arial",
                            fontWeight: "bold",
                            fontStyle: "normal",
                            textDecoration: "none",
                            textAlign: "center",
                            color: "#0f172a",
                            link: "",
                            rotation: 0,
                        },
                        {
                            id: "theme-1-subtitle",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "A polished cover slide for modern storytelling.",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add subtitle",
                            hasBeenEdited: true,
                            x: 150,
                            y: 170,
                            width: 660,
                            height: 60,
                            fontSize: 22,
                            fontFamily: "Arial",
                            fontWeight: "normal",
                            fontStyle: "normal",
                            textDecoration: "none",
                            textAlign: "center",
                            color: "#334155",
                            link: "",
                            rotation: 0,
                        },
                    ],
                },
                {
                    id: "slide-untitled-1b",
                    background: "#ffffff",
                    backgroundImage: "https://cdn.pixabay.com/photo/2026/05/14/03/06/03-06-32-708_1280.jpg",
                    backgroundType: "image",
                    layers: [
                        {
                            id: "theme-1b-overlay",
                            type: "shape",
                            shapeType: "rect",
                            x: 40,
                            y: 40,
                            width: 880,
                            height: 220,
                            fillColor: "rgba(15,23,42,0.72)",
                            strokeColor: "transparent",
                            strokeWidth: 0,
                            rotation: 0,
                            opacity: 0.88,
                            locked: false,
                        },
                        {
                            id: "theme-1b-title",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "Make it yours",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add title",
                            hasBeenEdited: true,
                            x: 70,
                            y: 70,
                            width: 820,
                            height: 110,
                            fontSize: 48,
                            fontFamily: "Arial",
                            fontWeight: "bold",
                            fontStyle: "normal",
                            textDecoration: "none",
                            textAlign: "center",
                            color: "#ffffff",
                            link: "",
                            rotation: 0,
                        },
                        {
                            id: "theme-1b-subtitle",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "A second slide uses the same image accent for strong continuity.",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add subtitle",
                            hasBeenEdited: true,
                            x: 150,
                            y: 190,
                            width: 660,
                            height: 60,
                            fontSize: 22,
                            fontFamily: "Arial",
                            fontWeight: "normal",
                            fontStyle: "normal",
                            textDecoration: "none",
                            textAlign: "center",
                            color: "#e2e8f0",
                            link: "",
                            rotation: 0,
                        },
                    ],
                },
            ],
        },
    },
    {
        id: "classic-theme",
        name: "Classic Theme",
        description: "Image background with classic white overlay text.",
        previewImage: "https://cdn.pixabay.com/photo/2026/05/18/11/39/11-39-44-709_1280.jpg",
        presentation: {
            title: "Classic Theme",
            slides: [
                {
                    id: "slide-classic-1",
                    background: "#ffffff",
                    backgroundImage: "https://cdn.pixabay.com/photo/2026/05/18/11/39/11-39-44-709_1280.jpg",
                    backgroundType: "image",
                    layers: [
                        {
                            id: "classic-text-1",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "Classic Theme",
                                            bold: true,
                                            fontSize: 60,
                                            color: "#ffffff",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add title",
                            hasBeenEdited: true,
                            x: 80,
                            y: 100,
                            width: 760,
                            height: 120,
                            fontSize: 60,
                            fontFamily: "Playfair Display",
                            fontWeight: "bold",
                            fontStyle: "normal",
                            textDecoration: "none",
                            textAlign: "left",
                            color: "#ffffff",
                            link: "",
                            rotation: 0,
                        },
                        {
                            id: "classic-text-2",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "A timeless design built for premium storytelling.",
                                            color: "#f8fafc",
                                            fontSize: 22,
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add subtitle",
                            hasBeenEdited: true,
                            x: 80,
                            y: 210,
                            width: 760,
                            height: 70,
                            fontSize: 22,
                            fontFamily: "Arial",
                            fontWeight: "normal",
                            fontStyle: "normal",
                            textDecoration: "none",
                            textAlign: "left",
                            color: "#f8fafc",
                            link: "",
                            rotation: 0,
                        },
                    ],
                },
                {
                    id: "slide-classic-2",
                    background: "#ffffff",
                    backgroundImage: "https://cdn.pixabay.com/photo/2026/05/18/11/39/11-39-44-709_1280.jpg",
                    backgroundType: "image",
                    layers: [
                        {
                            id: "classic-overlay",
                            type: "shape",
                            shapeType: "rect",
                            x: 60,
                            y: 80,
                            width: 840,
                            height: 200,
                            fillColor: "rgba(15,23,42,0.72)",
                            strokeColor: "transparent",
                            strokeWidth: 0,
                            rotation: 0,
                            opacity: 0.88,
                            locked: false,
                        },
                        {
                            id: "classic-text-3",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "Sophisticated continuation",
                                            bold: true,
                                            fontSize: 52,
                                            color: "#ffffff",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add title",
                            hasBeenEdited: true,
                            x: 90,
                            y: 100,
                            width: 780,
                            height: 110,
                            fontSize: 52,
                            fontFamily: "Playfair Display",
                            fontWeight: "bold",
                            fontStyle: "normal",
                            textDecoration: "none",
                            textAlign: "left",
                            color: "#ffffff",
                            link: "",
                            rotation: 0,
                        },
                        {
                            id: "classic-text-4",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "Keep the same premium background across slides for a cohesive feel.",
                                            color: "#e2e8f0",
                                            fontSize: 22,
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add subtitle",
                            hasBeenEdited: true,
                            x: 90,
                            y: 210,
                            width: 780,
                            height: 70,
                            fontSize: 22,
                            fontFamily: "Arial",
                            fontWeight: "normal",
                            fontStyle: "normal",
                            textDecoration: "none",
                            textAlign: "left",
                            color: "#e2e8f0",
                            link: "",
                            rotation: 0,
                        },
                    ],
                },
            ],
        },
    },
    {
        id: "storm-sequence",
        name: "Storm Sequence",
        description: "Sequential steps with strong photo accent.",
        previewImage: "https://cdn.pixabay.com/photo/2026/05/19/17/31/ceetje-storm-10288198_1280.jpg",
        presentation: {
            title: "Storm Sequence",
            slides: [
                {
                    id: "slide-sequence-1",
                    background: "#0f172a",
                    layers: [
                        {
                            id: "sequence-title",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "Storm Sequence",
                                            bold: true,
                                            fontSize: 42,
                                            color: "#ffffff",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add title",
                            hasBeenEdited: true,
                            x: 60,
                            y: 60,
                            width: 420,
                            height: 100,
                            fontSize: 54,
                            fontFamily: "Arial",
                            textAlign: "left",
                            color: "#ffffff",
                            rotation: 0,
                        },
                        {
                            id: "sequence-step-1",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "1. Define the challenge",
                                            fontSize: 24,
                                            color: "#f8fafc",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add text",
                            hasBeenEdited: true,
                            x: 60,
                            y: 180,
                            width: 420,
                            height: 50,
                            fontSize: 24,
                            fontFamily: "Arial",
                            textAlign: "left",
                            color: "#f8fafc",
                            rotation: 0,
                        },
                        {
                            id: "sequence-step-2",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "2. Align your team",
                                            fontSize: 24,
                                            color: "#cbd5e1",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add text",
                            hasBeenEdited: true,
                            x: 60,
                            y: 230,
                            width: 420,
                            height: 50,
                            fontSize: 24,
                            fontFamily: "Arial",
                            textAlign: "left",
                            color: "#cbd5e1",
                            rotation: 0,
                        },
                        {
                            id: "sequence-step-3",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "3. Deliver the outcome",
                                            fontSize: 24,
                                            color: "#94a3b8",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add text",
                            hasBeenEdited: true,
                            x: 60,
                            y: 280,
                            width: 420,
                            height: 50,
                            fontSize: 24,
                            fontFamily: "Arial",
                            textAlign: "left",
                            color: "#94a3b8",
                            rotation: 0,
                        },
                    ],
                },
                {
                    id: "slide-sequence-2",
                    background: "#0f172a",
                    layers: [
                        {
                            id: "sequence-image-a",
                            type: "image",
                            src: "https://cdn.pixabay.com/photo/2026/05/19/17/31/ceetje-storm-10288198_1280.jpg",
                            imageUrl: "https://cdn.pixabay.com/photo/2026/05/19/17/31/ceetje-storm-10288198_1280.jpg",
                            x: 520,
                            y: 60,
                            width: 380,
                            height: 320,
                            rotation: 0,
                            borderRadius: 24,
                            borderWidth: 0,
                            borderColor: "#ffffff",
                        },
                        {
                            id: "sequence-title-b",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "Storm Sequence",
                                            bold: true,
                                            fontSize: 54,
                                            color: "#ffffff",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add title",
                            hasBeenEdited: true,
                            x: 60,
                            y: 60,
                            width: 420,
                            height: 100,
                            fontSize: 54,
                            fontFamily: "Arial",
                            textAlign: "left",
                            color: "#ffffff",
                            rotation: 0,
                        },
                        {
                            id: "sequence-step-4",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "4. Capture momentum",
                                            fontSize: 24,
                                            color: "#f8fafc",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add text",
                            hasBeenEdited: true,
                            x: 60,
                            y: 180,
                            width: 420,
                            height: 50,
                            fontSize: 24,
                            fontFamily: "Arial",
                            textAlign: "left",
                            color: "#f8fafc",
                            rotation: 0,
                        },
                        {
                            id: "sequence-step-5",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "5. Keep the visuals bold and consistent.",
                                            fontSize: 24,
                                            color: "#cbd5e1",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add text",
                            hasBeenEdited: true,
                            x: 60,
                            y: 240,
                            width: 420,
                            height: 60,
                            fontSize: 24,
                            fontFamily: "Arial",
                            textAlign: "left",
                            color: "#cbd5e1",
                            rotation: 0,
                        },
                    ],
                },
            ],
        },
    },
    {
        id: "city-light",
        name: "City Light",
        description: "Bright city photo with clean text panels.",
        previewImage: "https://cdn.pixabay.com/photo/2025/11/07/07/24/city-768987_1280.jpg",
        presentation: {
            title: "City Light",
            slides: [
                {
                    id: "slide-city-1",
                    background: "#ffffff",
                    backgroundImage: "https://cdn.pixabay.com/photo/2025/11/07/07/24/city-768987_1280.jpg",
                    backgroundType: "image",
                    layers: [
                        {
                            id: "city-1-panel",
                            type: "shape",
                            shapeType: "rect",
                            x: 50,
                            y: 20,
                            width: 860,
                            height: 180,
                            fillColor: "rgba(15,23,42,0.78)",
                            strokeColor: "transparent",
                            strokeWidth: 0,
                            rotation: 0,
                            opacity: 0.95,
                            locked: false,
                        },
                        {
                            id: "city-1-title",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "City Light",
                                            bold: true,
                                            fontSize: 52,
                                            color: "#ffffff",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add title",
                            hasBeenEdited: true,
                            x: 70,
                            y: 40,
                            width: 820,
                            height: 90,
                            fontSize: 52,
                            fontFamily: "Arial",
                            textAlign: "left",
                            color: "#ffffff",
                            rotation: 0,
                        },
                        {
                            id: "city-1-subtitle",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "A luminous cover slide with room for your big idea.",
                                            fontSize: 22,
                                            color: "#e2e8f0",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add subtitle",
                            hasBeenEdited: true,
                            x: 70,
                            y: 120,
                            width: 820,
                            height: 60,
                            fontSize: 22,
                            fontFamily: "Arial",
                            textAlign: "left",
                            color: "#e2e8f0",
                            rotation: 0,
                        },
                    ],
                },
                {
                    id: "slide-city-2",
                    background: "#f8fafc",
                    layers: [
                        {
                            id: "city-2-card",
                            type: "shape",
                            shapeType: "rect",
                            x: 40,
                            y: 60,
                            width: 440,
                            height: 160,
                            fillColor: "#ffffff",
                            strokeColor: "#cbd5e1",
                            strokeWidth: 1,
                            rotation: 0,
                            opacity: 1,
                            locked: false,
                        },
                        {
                            id: "city-2-card-2",
                            type: "shape",
                            shapeType: "rect",
                            x: 520,
                            y: 220,
                            width: 400,
                            height: 190,
                            fillColor: "#e2e8f0",
                            strokeColor: "#94a3b8",
                            strokeWidth: 1,
                            rotation: 0,
                            opacity: 1,
                            locked: false,
                        },
                        {
                            id: "city-2-title",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "Urban ideas",
                                            bold: true,
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add title",
                            hasBeenEdited: true,
                            x: 70,
                            y: 80,
                            width: 820,
                            height: 90,
                            fontSize: 46,
                            fontFamily: "Arial",
                            textAlign: "left",
                            color: "#0f172a",
                            rotation: 0,
                        },
                        {
                            id: "city-2-text",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "A second slide with space for highlights and image callouts.",
                                            fontSize: 13,
                                            color: "#475569",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add subtitle",
                            hasBeenEdited: true,
                            x: 70,
                            y: 140,
                            width: 420,
                            height: 80,
                            fontSize: 20,
                            fontFamily: "Arial",
                            textAlign: "left",
                            color: "#475569",
                            rotation: 0,
                        },
                    ],
                },
            ],
        },
    },
    {
        id: "fresh-growth",
        name: "Fresh Growth",
        description: "Green growth shapes with a clean product panel.",
        previewImage: "https://cdn.pixabay.com/photo/2025/04/20/08/12/plant-715467_1280.jpg",
        presentation: {
            title: "Fresh Growth",
            slides: [
                {
                    id: "slide-growth-1",
                    background: "#effaf4",
                    layers: [
                        {
                            id: "growth-shape-1",
                            type: "shape",
                            shapeType: "rect",
                            x: 40,
                            y: 60,
                            width: 420,
                            height: 180,
                            fillColor: "#d1fae5",
                            strokeColor: "transparent",
                            strokeWidth: 0,
                            rotation: -4,
                            opacity: 1,
                            locked: false,
                        },
                        {
                            id: "growth-shape-2",
                            type: "shape",
                            shapeType: "rect",
                            x: 520,
                            y: 170,
                            width: 400,
                            height: 210,
                            fillColor: "#86efac",
                            strokeColor: "transparent",
                            strokeWidth: 0,
                            rotation: 6,
                            opacity: 1,
                            locked: false,
                        },
                        {
                            id: "growth-title",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "Fresh Growth",
                                            bold: true,
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add title",
                            hasBeenEdited: true,
                            x: 100,
                            y: 90,
                            width: 760,
                            height: 90,
                            fontSize: 48,
                            fontFamily: "Arial",
                            textAlign: "left",
                            color: "#0f172a",
                            rotation: 0,
                        },
                        {
                            id: "growth-subtitle",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "A fresh visual system for growth and impact.",
                                            fontSize: 20,
                                            color: "#14532d",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add subtitle",
                            hasBeenEdited: true,
                            x: 100,
                            y: 190,
                            width: 760,
                            height: 70,
                            fontSize: 20,
                            fontFamily: "Arial",
                            textAlign: "left",
                            color: "#14532d",
                            rotation: 0,
                        },
                    ],
                },
                {
                    id: "slide-growth-2",
                    background: "#ffffff",
                    layers: [
                        {
                            id: "growth-image",
                            type: "image",
                            src: "https://cdn.pixabay.com/photo/2025/04/20/08/12/plant-715467_1280.jpg",
                            imageUrl: "https://cdn.pixabay.com/photo/2025/04/20/08/12/plant-715467_1280.jpg",
                            x: 520,
                            y: 80,
                            width: 380,
                            height: 320,
                            rotation: 0,
                            borderRadius: 24,
                            borderWidth: 0,
                            borderColor: "#ffffff",
                        },
                        {
                            id: "growth-heading",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "Build with clarity",
                                            bold: true,
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add title",
                            hasBeenEdited: true,
                            x: 60,
                            y: 80,
                            width: 420,
                            height: 90,
                            fontSize: 46,
                            fontFamily: "Arial",
                            textAlign: "left",
                            color: "#0f172a",
                            rotation: 0,
                        },
                        {
                            id: "growth-bullet-1",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "• Strategy aligned with action",
                                            fontSize: 22,
                                            color: "#166534",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add text",
                            hasBeenEdited: true,
                            x: 60,
                            y: 180,
                            width: 420,
                            height: 50,
                            fontSize: 22,
                            fontFamily: "Arial",
                            textAlign: "left",
                            color: "#166534",
                            rotation: 0,
                        },
                        {
                            id: "growth-bullet-2",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "• Visuals that feel modern and calm",
                                            fontSize: 22,
                                            color: "#166534",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add text",
                            hasBeenEdited: true,
                            x: 60,
                            y: 240,
                            width: 420,
                            height: 60,
                            fontSize: 22,
                            fontFamily: "Arial",
                            textAlign: "left",
                            color: "#166534",
                            rotation: 0,
                        },
                    ],
                },
            ],
        },
    },
    {
        id: "bold-vision",
        name: "Bold Vision",
        description: "Dark, strong typography with accent color blocks.",
        previewImage: "https://cdn.pixabay.com/photo/2026/03/02/09/02/architecture-1234567_1280.jpg",
        presentation: {
            title: "Bold Vision",
            slides: [
                {
                    id: "slide-bold-1",
                    background: "#0f172a",
                    layers: [
                        {
                            id: "bold-1-banner",
                            type: "shape",
                            shapeType: "rect",
                            x: 40,
                            y: 60,
                            width: 880,
                            height: 120,
                            fillColor: "#f59e0b",
                            strokeColor: "transparent",
                            strokeWidth: 0,
                            rotation: 0,
                            opacity: 1,
                            locked: false,
                        },
                        {
                            id: "bold-1-title",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "Bold Vision",
                                            bold: true,
                                            fontSize: 56,
                                            color: "#ffffff",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add title",
                            hasBeenEdited: true,
                            x: 60,
                            y: 80,
                            width: 840,
                            height: 120,
                            fontSize: 56,
                            fontFamily: "Arial",
                            textAlign: "left",
                            color: "#ffffff",
                            rotation: 0,
                        },
                        {
                            id: "bold-1-subtitle",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "A strong, modern cover for creative presentations.",
                                            fontSize: 22,
                                            color: "#e2e8f0",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add subtitle",
                            hasBeenEdited: true,
                            x: 60,
                            y: 190,
                            width: 840,
                            height: 60,
                            fontSize: 22,
                            fontFamily: "Arial",
                            textAlign: "left",
                            color: "#e2e8f0",
                            rotation: 0,
                        },
                    ],
                },
                {
                    id: "slide-bold-2",
                    background: "#0f172a",
                    layers: [
                        {
                            id: "bold-2-shape",
                            type: "shape",
                            shapeType: "rect",
                            x: 40,
                            y: 80,
                            width: 420,
                            height: 220,
                            fillColor: "#1e293b",
                            strokeColor: "transparent",
                            strokeWidth: 0,
                            rotation: 0,
                            opacity: 1,
                            locked: false,
                        },
                        {
                            id: "bold-2-title",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "Take bold action",
                                            bold: true,
                                            fontSize: 46,
                                            color: "#ffffff",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add title",
                            hasBeenEdited: true,
                            x: 60,
                            y: 100,
                            width: 420,
                            height: 90,
                            fontSize: 46,
                            fontFamily: "Arial",
                            textAlign: "left",
                            color: "#ffffff",
                            rotation: 0,
                        },
                        {
                            id: "bold-2-text-1",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "• Present a bold mission",
                                            fontSize: 22,
                                            color: "#f8fafc",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add text",
                            hasBeenEdited: true,
                            x: 60,
                            y: 210,
                            width: 420,
                            height: 40,
                            fontSize: 22,
                            fontFamily: "Arial",
                            textAlign: "left",
                            color: "#f8fafc",
                            rotation: 0,
                        },
                        {
                            id: "bold-2-text-2",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "• Keep every section sharp and simple.",
                                            fontSize: 22,
                                            color: "#94a3b8",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add text",
                            hasBeenEdited: true,
                            x: 60,
                            y: 260,
                            width: 420,
                            height: 40,
                            fontSize: 22,
                            fontFamily: "Arial",
                            textAlign: "left",
                            color: "#94a3b8",
                            rotation: 0,
                        },
                    ],
                },
            ],
        },
    },
];
