export const STATIC_PRESENTATION_THEMES = [
    {
        id: "untitled-presentation-1",
        name: "Untitled Presentation",
        description: "Photo header with clean centered title.",
        previewImage: "https://cdn.pixabay.com/photo/2026/05/14/03/06/03-06-32-708_1280.jpg",
        presentation: {
            title: "Untitled Presentation",
            slides: [
                {
                    id: "slide-untitled-1",
                    background: "#ffffff",
                    backgroundImage: "https://cdn.pixabay.com/photo/2026/05/14/03/06/03-06-32-708_1280.jpg",
                    backgroundType: "image",
                    layers: [
                        {
                            id: "theme-1-overlay",
                            type: "shape",
                            shapeType: "rect",
                            x: 40,
                            y: 40,
                            width: 880,
                            height: 220,
                            fillColor: "rgba(255,255,255,0.88)",
                            strokeColor: "transparent",
                            strokeWidth: 0,
                            rotation: 0,
                            opacity: 0.88,
                            locked: false,
                        },
                        {
                            id: "theme-1-title",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "Untitled Presentation",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add title",
                            hasBeenEdited: true,
                            x: 70,
                            y: 70,
                            width: 820,
                            height: 110,
                            fontSize: 54,
                            fontFamily: "Arial",
                            fontWeight: "bold",
                            fontStyle: "normal",
                            textDecoration: "none",
                            textAlign: "center",
                            color: "#0f172a",
                            link: "",
                            rotation: 0,
                        },
                        {
                            id: "theme-1-subtitle",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "A polished cover slide for modern storytelling.",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add subtitle",
                            hasBeenEdited: true,
                            x: 150,
                            y: 170,
                            width: 660,
                            height: 60,
                            fontSize: 22,
                            fontFamily: "Arial",
                            fontWeight: "normal",
                            fontStyle: "normal",
                            textDecoration: "none",
                            textAlign: "center",
                            color: "#334155",
                            link: "",
                            rotation: 0,
                        },
                    ],
                },
                {
                    id: "slide-untitled-1b",
                    background: "#ffffff",
                    backgroundImage: "https://cdn.pixabay.com/photo/2026/05/14/03/06/03-06-32-708_1280.jpg",
                    backgroundType: "image",
                    layers: [
                        {
                            id: "theme-1b-overlay",
                            type: "shape",
                            shapeType: "rect",
                            x: 40,
                            y: 40,
                            width: 880,
                            height: 220,
                            fillColor: "rgba(15,23,42,0.72)",
                            strokeColor: "transparent",
                            strokeWidth: 0,
                            rotation: 0,
                            opacity: 0.88,
                            locked: false,
                        },
                        {
                            id: "theme-1b-title",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "Make it yours",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add title",
                            hasBeenEdited: true,
                            x: 70,
                            y: 70,
                            width: 820,
                            height: 110,
                            fontSize: 48,
                            fontFamily: "Arial",
                            fontWeight: "bold",
                            fontStyle: "normal",
                            textDecoration: "none",
                            textAlign: "center",
                            color: "#ffffff",
                            link: "",
                            rotation: 0,
                        },
                        {
                            id: "theme-1b-subtitle",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "A second slide uses the same image accent for strong continuity.",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add subtitle",
                            hasBeenEdited: true,
                            x: 150,
                            y: 190,
                            width: 660,
                            height: 60,
                            fontSize: 22,
                            fontFamily: "Arial",
                            fontWeight: "normal",
                            fontStyle: "normal",
                            textDecoration: "none",
                            textAlign: "center",
                            color: "#e2e8f0",
                            link: "",
                            rotation: 0,
                        },
                    ],
                },
            ],
        },
    },
    {
        id: "untitled-presentation-2",
        name: "Untitled Presentation",
        description: "Zig-zag layout with dual accent panels.",
        previewImage: "https://cdn.pixabay.com/photo/2026/05/07/15/15/15-15-51-333_1280.jpg",
        presentation: {
            title: "Untitled Presentation",
            slides: [
                {
                    id: "slide-untitled-2",
                    background: "#f8fafc",
                    layers: [
                        {
                            id: "theme-2-shape-1",
                            type: "shape",
                            shapeType: "rect",
                            x: 40,
                            y: 40,
                            width: 440,
                            height: 200,
                            fillColor: "#e2e8f0",
                            strokeColor: "#64748b",
                            strokeWidth: 0,
                            rotation: -4,
                            opacity: 1,
                            locked: false,
                        },
                        {
                            id: "theme-2-shape-2",
                            type: "shape",
                            shapeType: "rect",
                            x: 520,
                            y: 180,
                            width: 420,
                            height: 200,
                            fillColor: "#c7d2fe",
                            strokeColor: "#4338ca",
                            strokeWidth: 0,
                            rotation: 5,
                            opacity: 1,
                            locked: false,
                        },
                        {
                            id: "theme-2-shape-3",
                            type: "shape",
                            shapeType: "rect",
                            x: 40,
                            y: 320,
                            width: 440,
                            height: 180,
                            fillColor: "#fef3c7",
                            strokeColor: "#b45309",
                            strokeWidth: 0,
                            rotation: -3,
                            opacity: 1,
                            locked: false,
                        },
                        {
                            id: "theme-2-text-1",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "Untitled Presentation",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add title",
                            hasBeenEdited: true,
                            x: 100,
                            y: 90,
                            width: 760,
                            height: 100,
                            fontSize: 44,
                            fontFamily: "Arial",
                            fontWeight: "bold",
                            fontStyle: "normal",
                            textDecoration: "none",
                            textAlign: "left",
                            color: "#0f172a",
                            link: "",
                            rotation: 0,
                        },
                        {
                            id: "theme-2-text-2",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "A dynamic zig-zag template for strong visual flow.",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add subtitle",
                            hasBeenEdited: true,
                            x: 100,
                            y: 190,
                            width: 760,
                            height: 60,
                            fontSize: 20,
                            fontFamily: "Arial",
                            fontWeight: "normal",
                            fontStyle: "normal",
                            textDecoration: "none",
                            textAlign: "left",
                            color: "#475569",
                            link: "",
                            rotation: 0,
                        },
                    ],
                },
                {
                    id: "slide-untitled-2b",
                    background: "#f8fafc",
                    layers: [
                        {
                            id: "theme-2b-shape-1",
                            type: "shape",
                            shapeType: "rect",
                            x: 40,
                            y: 60,
                            width: 440,
                            height: 180,
                            fillColor: "#dbeafe",
                            strokeColor: "transparent",
                            strokeWidth: 0,
                            rotation: -4,
                            opacity: 1,
                            locked: false,
                        },
                        {
                            id: "theme-2b-shape-2",
                            type: "shape",
                            shapeType: "rect",
                            x: 520,
                            y: 140,
                            width: 420,
                            height: 180,
                            fillColor: "#ede9fe",
                            strokeColor: "transparent",
                            strokeWidth: 0,
                            rotation: 5,
                            opacity: 1,
                            locked: false,
                        },
                        {
                            id: "theme-2b-text-1",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "Continue the rhythm",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add title",
                            hasBeenEdited: true,
                            x: 100,
                            y: 90,
                            width: 760,
                            height: 100,
                            fontSize: 42,
                            fontFamily: "Arial",
                            fontWeight: "bold",
                            fontStyle: "normal",
                            textDecoration: "none",
                            textAlign: "left",
                            color: "#0f172a",
                            link: "",
                            rotation: 0,
                        },
                        {
                            id: "theme-2b-text-2",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "Add another page with the same bold accent and layout flow.",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add subtitle",
                            hasBeenEdited: true,
                            x: 100,
                            y: 200,
                            width: 760,
                            height: 60,
                            fontSize: 20,
                            fontFamily: "Arial",
                            fontWeight: "normal",
                            fontStyle: "normal",
                            textDecoration: "none",
                            textAlign: "left",
                            color: "#475569",
                            link: "",
                            rotation: 0,
                        },
                    ],
                },
            ],
        },
    },
    {
        id: "classic-theme",
        name: "Classic Theme",
        description: "Image background with classic white overlay text.",
        previewImage: "https://cdn.pixabay.com/photo/2026/05/18/11/39/11-39-44-709_1280.jpg",
        presentation: {
            title: "Classic Theme",
            slides: [
                {
                    id: "slide-classic-1",
                    background: "#ffffff",
                    backgroundImage: "https://cdn.pixabay.com/photo/2026/05/18/11/39/11-39-44-709_1280.jpg",
                    backgroundType: "image",
                    layers: [
                        {
                            id: "classic-text-1",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "Classic Theme",
                                            bold: true,
                                            fontSize: 60,
                                            color: "#ffffff",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add title",
                            hasBeenEdited: true,
                            x: 80,
                            y: 100,
                            width: 760,
                            height: 120,
                            fontSize: 60,
                            fontFamily: "Playfair Display",
                            fontWeight: "bold",
                            fontStyle: "normal",
                            textDecoration: "none",
                            textAlign: "left",
                            color: "#ffffff",
                            link: "",
                            rotation: 0,
                        },
                        {
                            id: "classic-text-2",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "A timeless design built for premium storytelling.",
                                            color: "#f8fafc",
                                            fontSize: 22,
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add subtitle",
                            hasBeenEdited: true,
                            x: 80,
                            y: 210,
                            width: 760,
                            height: 70,
                            fontSize: 22,
                            fontFamily: "Arial",
                            fontWeight: "normal",
                            fontStyle: "normal",
                            textDecoration: "none",
                            textAlign: "left",
                            color: "#f8fafc",
                            link: "",
                            rotation: 0,
                        },
                    ],
                },
                {
                    id: "slide-classic-2",
                    background: "#ffffff",
                    backgroundImage: "https://cdn.pixabay.com/photo/2026/05/18/11/39/11-39-44-709_1280.jpg",
                    backgroundType: "image",
                    layers: [
                        {
                            id: "classic-overlay",
                            type: "shape",
                            shapeType: "rect",
                            x: 60,
                            y: 80,
                            width: 840,
                            height: 200,
                            fillColor: "rgba(15,23,42,0.72)",
                            strokeColor: "transparent",
                            strokeWidth: 0,
                            rotation: 0,
                            opacity: 0.88,
                            locked: false,
                        },
                        {
                            id: "classic-text-3",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "Sophisticated continuation",
                                            bold: true,
                                            fontSize: 52,
                                            color: "#ffffff",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add title",
                            hasBeenEdited: true,
                            x: 90,
                            y: 100,
                            width: 780,
                            height: 110,
                            fontSize: 52,
                            fontFamily: "Playfair Display",
                            fontWeight: "bold",
                            fontStyle: "normal",
                            textDecoration: "none",
                            textAlign: "left",
                            color: "#ffffff",
                            link: "",
                            rotation: 0,
                        },
                        {
                            id: "classic-text-4",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "Keep the same premium background across slides for a cohesive feel.",
                                            color: "#e2e8f0",
                                            fontSize: 22,
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add subtitle",
                            hasBeenEdited: true,
                            x: 90,
                            y: 210,
                            width: 780,
                            height: 70,
                            fontSize: 22,
                            fontFamily: "Arial",
                            fontWeight: "normal",
                            fontStyle: "normal",
                            textDecoration: "none",
                            textAlign: "left",
                            color: "#e2e8f0",
                            link: "",
                            rotation: 0,
                        },
                    ],
                },
            ],
        },
    },
    {
        id: "zigzag-flow",
        name: "Zig Zag Flow",
        description: "Bold zig-zag shape blocks with supporting text.",
        previewImage: "https://cdn.pixabay.com/photo/2026/01/30/23/52/brown-pelican-10096739_1280.jpg",
        presentation: {
            title: "Zig Zag Flow",
            slides: [
                {
                    id: "slide-zigzag-1",
                    background: "#f8fafc",
                    layers: [
                        {
                            id: "zigzag-shape-1",
                            type: "shape",
                            shapeType: "rect",
                            x: 40,
                            y: 60,
                            width: 420,
                            height: 170,
                            fillColor: "#fde68a",
                            strokeColor: "#f59e0b",
                            strokeWidth: 0,
                            rotation: -8,
                            opacity: 1,
                            locked: false,
                        },
                        {
                            id: "zigzag-shape-2",
                            type: "shape",
                            shapeType: "rect",
                            x: 500,
                            y: 170,
                            width: 420,
                            height: 170,
                            fillColor: "#bae6fd",
                            strokeColor: "#0284c7",
                            strokeWidth: 0,
                            rotation: 7,
                            opacity: 1,
                            locked: false,
                        },
                        {
                            id: "zigzag-shape-3",
                            type: "shape",
                            shapeType: "rect",
                            x: 40,
                            y: 290,
                            width: 420,
                            height: 170,
                            fillColor: "#d4f2d4",
                            strokeColor: "#16a34a",
                            strokeWidth: 0,
                            rotation: -5,
                            opacity: 1,
                            locked: false,
                        },
                        {
                            id: "zigzag-title",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "Zig Zag Flow",
                                            bold: true,
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add title",
                            hasBeenEdited: true,
                            x: 100,
                            y: 90,
                            width: 720,
                            height: 90,
                            fontSize: 48,
                            fontFamily: "Arial",
                            textAlign: "left",
                            color: "#0f172a",
                            rotation: 0,
                        },
                        {
                            id: "zigzag-subtitle",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "Designed for step-by-step stories with strong momentum.",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add subtitle",
                            hasBeenEdited: true,
                            x: 100,
                            y: 160,
                            width: 720,
                            height: 60,
                            fontSize: 20,
                            fontFamily: "Arial",
                            textAlign: "left",
                            color: "#475569",
                            rotation: 0,
                        },
                    ],
                },
                {
                    id: "slide-zigzag-2",
                    background: "#f8fafc",
                    layers: [
                        {
                            id: "zigzag-shape-1b",
                            type: "shape",
                            shapeType: "rect",
                            x: 80,
                            y: 70,
                            width: 400,
                            height: 170,
                            fillColor: "#fde68a",
                            strokeColor: "transparent",
                            strokeWidth: 0,
                            rotation: -7,
                            opacity: 1,
                            locked: false,
                        },
                        {
                            id: "zigzag-shape-2b",
                            type: "shape",
                            shapeType: "rect",
                            x: 520,
                            y: 200,
                            width: 400,
                            height: 170,
                            fillColor: "#bae6fd",
                            strokeColor: "transparent",
                            strokeWidth: 0,
                            rotation: 6,
                            opacity: 1,
                            locked: false,
                        },
                        {
                            id: "zigzag-title-2",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "Continue the pattern",
                                            bold: true,
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add title",
                            hasBeenEdited: true,
                            x: 100,
                            y: 90,
                            width: 760,
                            height: 90,
                            fontSize: 48,
                            fontFamily: "Arial",
                            textAlign: "left",
                            color: "#0f172a",
                            rotation: 0,
                        },
                        {
                            id: "zigzag-subtitle-2",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "A second slide keeps your narrative moving with the same visual language.",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add subtitle",
                            hasBeenEdited: true,
                            x: 100,
                            y: 170,
                            width: 760,
                            height: 60,
                            fontSize: 20,
                            fontFamily: "Arial",
                            textAlign: "left",
                            color: "#475569",
                            rotation: 0,
                        },
                    ],
                },
            ],
        },
    },
    {
        id: "storm-sequence",
        name: "Storm Sequence",
        description: "Sequential steps with strong photo accent.",
        previewImage: "https://cdn.pixabay.com/photo/2026/05/19/17/31/ceetje-storm-10288198_1280.jpg",
        presentation: {
            title: "Storm Sequence",
            slides: [
                {
                    id: "slide-sequence-1",
                    background: "#0f172a",
                    layers: [
                        {
                            id: "sequence-image",
                            type: "image",
                            src: "https://cdn.pixabay.com/photo/2026/05/19/17/31/ceetje-storm-10288198_1280.jpg",
                            imageUrl: "https://cdn.pixabay.com/photo/2026/05/19/17/31/ceetje-storm-10288198_1280.jpg",
                            x: 440,
                            y: 80,
                            width: 380,
                            height: 320,
                            rotation: 0,
                            borderRadius: 24,
                            borderWidth: 0,
                            borderColor: "#ffffff",
                        },
                        {
                            id: "sequence-title",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "Storm Sequence",
                                            bold: true,
                                            fontSize: 42,
                                            color: "#ffffff",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add title",
                            hasBeenEdited: true,
                            x: 60,
                            y: 60,
                            width: 420,
                            height: 100,
                            fontSize: 54,
                            fontFamily: "Arial",
                            textAlign: "left",
                            color: "#ffffff",
                            rotation: 0,
                        },
                        {
                            id: "sequence-step-1",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "1. Define the challenge",
                                            fontSize: 24,
                                            color: "#f8fafc",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add text",
                            hasBeenEdited: true,
                            x: 60,
                            y: 180,
                            width: 420,
                            height: 50,
                            fontSize: 24,
                            fontFamily: "Arial",
                            textAlign: "left",
                            color: "#f8fafc",
                            rotation: 0,
                        },
                        {
                            id: "sequence-step-2",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "2. Align your team",
                                            fontSize: 24,
                                            color: "#cbd5e1",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add text",
                            hasBeenEdited: true,
                            x: 60,
                            y: 230,
                            width: 420,
                            height: 50,
                            fontSize: 24,
                            fontFamily: "Arial",
                            textAlign: "left",
                            color: "#cbd5e1",
                            rotation: 0,
                        },
                        {
                            id: "sequence-step-3",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "3. Deliver the outcome",
                                            fontSize: 24,
                                            color: "#94a3b8",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add text",
                            hasBeenEdited: true,
                            x: 60,
                            y: 280,
                            width: 420,
                            height: 50,
                            fontSize: 24,
                            fontFamily: "Arial",
                            textAlign: "left",
                            color: "#94a3b8",
                            rotation: 0,
                        },
                    ],
                },
                {
                    id: "slide-sequence-2",
                    background: "#0f172a",
                    layers: [
                        {
                            id: "sequence-image-b",
                            type: "image",
                            src: "https://cdn.pixabay.com/photo/2026/05/19/17/31/ceetje-storm-10288198_1280.jpg",
                            imageUrl: "https://cdn.pixabay.com/photo/2026/05/19/17/31/ceetje-storm-10288198_1280.jpg",
                            x: 440,
                            y: 80,
                            width: 380,
                            height: 320,
                            rotation: 0,
                            borderRadius: 24,
                            borderWidth: 0,
                            borderColor: "#ffffff",
                        },
                        {
                            id: "sequence-title-b",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "Storm Sequence",
                                            bold: true,
                                            fontSize: 42,
                                            color: "#ffffff",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add title",
                            hasBeenEdited: true,
                            x: 60,
                            y: 60,
                            width: 420,
                            height: 100,
                            fontSize: 54,
                            fontFamily: "Arial",
                            textAlign: "left",
                            color: "#ffffff",
                            rotation: 0,
                        },
                        {
                            id: "sequence-step-4",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "4. Capture momentum",
                                            fontSize: 24,
                                            color: "#f8fafc",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add text",
                            hasBeenEdited: true,
                            x: 60,
                            y: 180,
                            width: 420,
                            height: 50,
                            fontSize: 24,
                            fontFamily: "Arial",
                            textAlign: "left",
                            color: "#f8fafc",
                            rotation: 0,
                        },
                        {
                            id: "sequence-step-5",
                            type: "text",
                            content: [
                                {
                                    type: "paragraph",
                                    children: [
                                        {
                                            text: "5. Keep the visuals bold and consistent.",
                                            fontSize: 24,
                                            color: "#cbd5e1",
                                        },
                                    ],
                                },
                            ],
                            placeholder: "Double click to add text",
                            hasBeenEdited: true,
                            x: 60,
                            y: 240,
                            width: 420,
                            height: 60,
                            fontSize: 24,
                            fontFamily: "Arial",
                            textAlign: "left",
                            color: "#cbd5e1",
                            rotation: 0,
                        },
                    ],
                },
            ],
        },
    },
];
